# Generated by Django 6.0.3 on 2026-04-30 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_charges', models.FloatField(default=0)),
                ('food_charges', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
